"""
Standard sRGB ICC Profile Provider for PDF/A OutputIntent.
Provides embedded standard sRGB IEC61966-2.1 ICC profile data.
"""

import base64
from pathlib import Path

# Standard sRGB IEC61966-2.1 ICC Profile (3144 bytes)
_SRGB_ICC_B64 = (
    "AAAMSExpbm8CEAAAbW50clJHQiBYWVogB84AAgAJAAYAMQAAYWNzcE1TRlQAAAAASUVDIHNSR0IA"
    "AAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1IUCAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAARY3BydAAAAVAAAAAzZGVzYwAAAYQAAABsd3RwdAAAAfAAAAAUYmtw"
    "dAAAAgQAAAAUclhZWgAAAhgAAAAUZ1hZWgAAAiwAAAAUYlhZWgAAAkAAAAAUZG1uZAAAAlQAAABw"
    "ZG1kZAAAAsQAAACIdnVlZAAAA0wAAACGdmlldwAAA9QAAAAkbHVtaQAAA/gAAAAUbWVhcwAABAwA"
    "AAAkdGVjaAAABDAAAAAMclRSQwAABDwAAAgMZ1RSQwAABDwAAAgMYlRSQwAABDwAAAgMdGV4dAAA"
    "AABDb3B5cmlnaHQgKGMpIDE5OTggSGV3bGV0dC1QYWNrYXJkIENvbXBhbnkAAGRlc2MAAAAAAAAA"
    "EnNSR0IgSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAASc1JHQiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAADzUQABAAAA"
    "ARbMWFlaIAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAA"
    "t4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9kZXNjAAAAAAAAABZJRUMgaHR0cDovL3d3dy5pZWMu"
    "Y2gAAAAAAAAAAAAAABZJRUMgaHR0cDovL3d3dy5pZWMuY2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGVzYwAAAAAAAAAuSUVDIDYxOTY2LTIuMSBEZWZhdWx0"
    "IFJHQiBjb2xvdXIgc3BhY2UgLSBzUkdCAAAAAAAAAAAAAAAuSUVDIDYxOTY2LTIuMSBEZWZhdWx0"
    "IFJHQiBjb2xvdXIgc3BhY2UgLSBzUkdCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRlc2MAAAAAAAAA"
    "LFJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAACxS"
    "ZWZlcmVuY2UgVmlld2luZyBDb25kaXRpb24gaW4gSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAB2aWV3AAAAAAATpP4AFF8uABDPFAAD7cwABBMLAANcngAAAAFYWVogAAAAAABM"
    "CVYAUAAAAFcf55N2Y3d3AAAAAAABAAAAAQEBAQAAAAEAAAABAQEBAAAAAQEBAQEAAAAAAAAAAHBh"
    "cmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbSFJHQwAAAAAAAAMAAAABVFJDAAAAAAAEPAAA"
    "AAFVUkNBAAAAAAAEPAAAAAFVUkNBAAAAAAAEPAAAAAEUZXRjAAAAAAAAMAAAABB1bml2AAAAAAA8"
    "AAAAG2RhdGEAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
)


def get_srgb_icc_bytes() -> bytes:
    """
    Returns standard sRGB IEC61966-2.1 ICC profile bytes.
    First tries local file/system path if available, otherwise returns embedded profile.
    """
    system_paths = [
        "/System/Library/ColorSync/Profiles/sRGB Profile.icc",
        "/usr/share/color/icc/sRGB.icc",
        "/usr/share/color/icc/colord/sRGB.icc",
    ]
    for path in system_paths:
        p = Path(path)
        if p.exists() and p.is_file():
            try:
                return p.read_bytes()
            except Exception:
                pass

    return base64.b64decode(_SRGB_ICC_B64)
